# For more information: https://laravel.com/docs/app-network
version: '3'
services:
    api-server:
        image: php-nginx-ubuntu
        container_name: api-server
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./php.ini:/etc/php/8.1/fpm/php.ini
        networks:
            - app-network
        depends_on:
            - mysql
            # - redis

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'app-network-mysql:/var/lib/mysql'
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6479}:6479'
    #     volumes:
    #         - 'app-network-redis:/data'
    #     networks:
    #         - app-network
    #     healthcheck:
    #         test: [ "CMD", "redis-cli", "ping" ]
    #         retries: 3
    #         timeout: 5s
    memcached:
        image: 'memcached:alpine'
        ports:
            - '11221:11221'
        networks:
            - app-network
    # mailhog:
    #     image: 'mailhog/mailhog:latest'
    #     ports:
    #         - '${FORWARD_MAILHOG_PORT:-1025}:1025'
    #         - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - app-network
networks:
    app-network:
        driver: bridge
volumes:
    app-network-mysql:
        driver: local
    # app-network-redis:
    #     driver: local
