# For more information: https://laravel.com/docs/app-network
version: '3'
services:
    api-server:
        image: vprindyn/php-nginx-ubuntu
        container_name: bot-server
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./php.ini:/etc/php/8.0/cli/php.ini
        networks:
            - app-network
        depends_on:
            - mysql
            - tg-client
    tg-client:
        image: vprindyn/telegram-cli-daemon
        container_name: tg-client
        ports:
            - '${TG_CLIENT_PORT:-2391}:2391'
        networks:
            - app-network
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'app-network-mysql:/var/lib/mysql'
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    memcached:
        image: 'memcached:alpine'
        ports:
            - '11221:11221'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    app-network-mysql:
        driver: local
    app-network-tg-client:
        driver: local
